# -*- coding: utf-8 -*-
"""nlu-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_MYPWEj2HvS7mqHMjY2XPvzx3lNTTnF
"""

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import torch.optim as optim
from nltk.translate.bleu_score import corpus_bleu
import time
import numpy as np
from collections import defaultdict

"""# LSTM"""

train_losses_lstm = []
train_losses_transformer = []
ablation_results = defaultdict(dict)

class NMTDataset(Dataset):
    def __init__(self, english_file, hindi_file, max_length=50,
                 english_vocab=None, hindi_vocab=None):
        with open(english_file, 'r', encoding='utf-8') as f:
            self.english_sentences = f.readlines()
        with open(hindi_file, 'r', encoding='utf-8') as f:
            self.hindi_sentences = f.readlines()

        self.english_tokens = [['<sos>'] + sentence.strip().split()[:max_length] + ['<eos>']
                              for sentence in self.english_sentences]
        self.hindi_tokens = [['<sos>'] + sentence.strip().split()[:max_length] + ['<eos>']
                            for sentence in self.hindi_sentences]

        if english_vocab and hindi_vocab:
            self.english_vocab = english_vocab
            self.hindi_vocab = hindi_vocab
        else:
            self.english_vocab = self.create_vocabulary(self.english_tokens)
            self.hindi_vocab = self.create_vocabulary(self.hindi_tokens)

        if not english_vocab:
            self.english_embeddings = self.create_embeddings(self.english_vocab)
            self.hindi_embeddings = self.create_embeddings(self.hindi_vocab)
        else:
            self.english_embeddings = None
            self.hindi_embeddings = None

    def create_vocabulary(self, tokenized_sentences):
        vocab = {'<pad>': 0, '<sos>': 1, '<eos>': 2, '<unk>': 3}
        current_index = 4
        for sentence in tokenized_sentences:
            for token in sentence:
                if token not in vocab:
                    vocab[token] = current_index
                    current_index += 1
        return vocab

    def create_embeddings(self, vocab, embedding_dim=300):
        embeddings = torch.zeros((len(vocab), embedding_dim))
        nn.init.xavier_uniform_(embeddings)
        return embeddings

    def __len__(self):
        return len(self.english_sentences)

    def __getitem__(self, idx):
        eng_indices = [self.english_vocab.get(token, self.english_vocab['<unk>']) for token in self.english_tokens[idx]]
        hindi_indices = [self.hindi_vocab.get(token, self.hindi_vocab['<unk>']) for token in self.hindi_tokens[idx]] if idx < len(self.hindi_tokens) else []
        return {
            'english': torch.tensor(eng_indices, dtype=torch.long),
            'hindi': torch.tensor(hindi_indices, dtype=torch.long)
        }

def collate_fn(batch):
    batch.sort(key=lambda x: len(x['english']), reverse=True)
    english_sequences = [item['english'] for item in batch]
    hindi_sequences = [item['hindi'] for item in batch]
    english_padded = pad_sequence(english_sequences, batch_first=True, padding_value=0)
    hindi_padded = pad_sequence(hindi_sequences, batch_first=True, padding_value=0)
    return {'english': english_padded, 'hindi': hindi_padded}

def calculate_bleu_score(hypotheses, references):
    # Format references as a list of lists (each sublist contains references for a hypothesis)
    formatted_references = [[ref] for ref in references]  # Ensure each hypothesis has a list of references
    return corpus_bleu(formatted_references, hypotheses)

def evaluate_model(model, test_loader, device, hindi_vocab, english_vocab=None, model_type='lstm'):
    model.eval()
    references = []
    hypotheses = []
    with torch.no_grad():
        for batch in test_loader:
            src = batch['english'].to(device)
            trg = batch['hindi'].to(device)
            if model_type == 'lstm':
                _, (hidden, cell) = model.encoder(src)
                num_layers = model.decoder.rnn.num_layers
                hidden = hidden.repeat(num_layers, 1, 1)
                cell = cell.repeat(num_layers, 1, 1)
                decoder_input = torch.ones(trg.size(0), dtype=torch.long, device=device) * hindi_vocab['<sos>']
                predicted_tokens = []
                for _ in range(trg.shape[1]-1):
                    decoder_output, (hidden, cell) = model.decoder(decoder_input, (hidden, cell))
                    predicted_token = decoder_output.argmax(1)
                    predicted_tokens.append(predicted_token)
                    decoder_input = predicted_token
                predicted_tokens = torch.stack(predicted_tokens).T
            else:  # Transformer
                max_len = trg.shape[1] - 1
                batch_size = src.size(0)
                predicted_tokens = torch.ones(batch_size, 1).fill_(hindi_vocab['<sos>']).long().to(device)

                for _ in range(max_len):
                    trg_mask = model.transformer.generate_square_subsequent_mask(predicted_tokens.size(1)).to(device)
                    output = model(
                        src,
                        predicted_tokens,
                        src_key_padding_mask=(src == 0),
                        tgt_mask=trg_mask,
                        tgt_key_padding_mask=(predicted_tokens == 0)
                    )
                    next_token = output.argmax(2)[:, -1].unsqueeze(1)
                    predicted_tokens = torch.cat([predicted_tokens, next_token], dim=1)

            for i in range(src.shape[0]):
                ref_tokens = [hindi_vocab.get(idx.item(), '<unk>') for idx in trg[i, 1:] if idx.item() != 0]
                hyp_tokens = [hindi_vocab.get(idx.item(), '<unk>') for idx in predicted_tokens[i] if idx.item() != 0]
                references.append(ref_tokens)  # Removed extra list wrapping
                hypotheses.append(hyp_tokens)
    bleu = calculate_bleu_score(hypotheses, references)
    return bleu

class LSTMEncoder(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers=2, dropout=0.2):
        super(LSTMEncoder, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim, hidden_dim, num_layers,
                            batch_first=True, dropout=dropout, bidirectional=True)
        self.fc = nn.Linear(hidden_dim * 2, hidden_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        outputs, (hidden, cell) = self.rnn(embedded)
        hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1)
        cell = torch.cat((cell[-2,:,:], cell[-1,:,:]), dim=1)
        hidden = self.fc(hidden).unsqueeze(0)
        cell = self.fc(cell).unsqueeze(0)
        return outputs, (hidden, cell)

class LSTMDecoder(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers=2, dropout=0.2):
        super(LSTMDecoder, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim, hidden_dim, num_layers,
                            batch_first=True, dropout=dropout)
        self.fc_out = nn.Linear(hidden_dim, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, hidden):
        x = x.unsqueeze(1)
        embedded = self.dropout(self.embedding(x))
        output, (hidden, cell) = self.rnn(embedded, hidden)
        prediction = self.fc_out(output.squeeze(1))
        return prediction, (hidden, cell)

class LSTMSeq2SeqModel(nn.Module):
    def __init__(self, encoder, decoder):
        super(LSTMSeq2SeqModel, self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src, trg):
        _, (hidden, cell) = self.encoder(src)
        num_layers = self.decoder.rnn.num_layers
        hidden = hidden.repeat(num_layers, 1, 1)
        cell = cell.repeat(num_layers, 1, 1)
        outputs = torch.zeros(trg.shape[0], trg.shape[1], self.decoder.fc_out.out_features).to(trg.device)
        decoder_input = trg[:, 0]
        for t in range(1, trg.shape[1]):
            decoder_output, (hidden, cell) = self.decoder(decoder_input, (hidden, cell))
            outputs[:, t, :] = decoder_output
            decoder_input = trg[:, t]
        return outputs

# Transformer model components
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-torch.log(torch.tensor(10000.0)) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]

class TransformerModel(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model=512, nhead=8,
                 num_encoder_layers=6, num_decoder_layers=6, dim_feedforward=2048, dropout=0.1):
        super(TransformerModel, self).__init__()
        self.src_embedding = nn.Embedding(src_vocab_size, d_model)
        self.tgt_embedding = nn.Embedding(tgt_vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(d_model)

        # Set batch_first=True to match our data format
        self.transformer = nn.Transformer(
            d_model=d_model,
            nhead=nhead,
            num_encoder_layers=num_encoder_layers,
            num_decoder_layers=num_decoder_layers,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True  # Ensure proper batch format
        )
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

    def forward(self, src, trg, src_mask=None, tgt_mask=None, memory_mask=None,
                src_key_padding_mask=None, tgt_key_padding_mask=None, memory_key_padding_mask=None):
        # Embed and add positional encoding
        src_emb = self.positional_encoding(self.src_embedding(src))
        trg_emb = self.positional_encoding(self.tgt_embedding(trg))

        # Generate target mask if not provided
        if tgt_mask is None and trg is not None:
            tgt_mask = self.transformer.generate_square_subsequent_mask(trg.size(1)).to(trg.device)

        # Transformer forward pass with corrected parameter names
        output = self.transformer(
            src_emb, trg_emb,
            src_mask=src_mask,
            tgt_mask=tgt_mask,
            memory_mask=memory_mask,
            src_key_padding_mask=src_key_padding_mask,
            tgt_key_padding_mask=tgt_key_padding_mask,
            memory_key_padding_mask=memory_key_padding_mask
        )
        return self.fc_out(output)

def create_masks(src, trg, pad_idx):
    src_mask = (src == pad_idx)
    trg_mask = (trg == pad_idx)
    return src_mask, trg_mask

def train_model(model, train_loader, criterion, optimizer, device, model_type='lstm'):
    model.train()
    total_loss = 0
    for batch in train_loader:
        src = batch['english'].to(device)
        trg = batch['hindi'].to(device)
        optimizer.zero_grad()

        if model_type == 'transformer':
            # Use teacher forcing: decoder input is trg[:-1], target is trg[1:]
            trg_input = trg[:, :-1]
            trg_target = trg[:, 1:]

            # Create padding masks
            src_padding_mask = (src == 0)
            trg_padding_mask = (trg_input == 0)

            outputs = model(
                src, trg_input,
                src_key_padding_mask=src_padding_mask,
                tgt_key_padding_mask=trg_padding_mask
            )

            # Reshape for loss calculation
            outputs = outputs.reshape(-1, outputs.shape[-1])
            trg_target = trg_target.reshape(-1)

            loss = criterion(outputs, trg_target)
        else:
            outputs = model(src, trg)
            outputs = outputs[:, 1:].reshape(-1, outputs.shape[-1])
            trg = trg[:, 1:].reshape(-1)
            loss = criterion(outputs, trg)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1)
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(train_loader)


def display_sample_translations(model, test_loader, device, hindi_vocab, reverse_hindi_vocab, reverse_english_vocab, model_type='lstm', num_samples=5):
    model.eval()
    samples = []

    with torch.no_grad():
        for batch in test_loader:
            src = batch['english'].to(device)
            trg = batch['hindi'].to(device)

            if model_type == 'lstm':
                _, (hidden, cell) = model.encoder(src)
                num_layers = model.decoder.rnn.num_layers
                hidden = hidden.repeat(num_layers, 1, 1)
                cell = cell.repeat(num_layers, 1, 1)

                decoder_input = torch.ones(trg.size(0), dtype=torch.long, device=device) * hindi_vocab['<sos>']
                predicted_tokens = []

                for _ in range(50):  # Maximum length limit
                    decoder_output, (hidden, cell) = model.decoder(decoder_input, (hidden, cell))
                    predicted_token = decoder_output.argmax(1)
                    predicted_tokens.append(predicted_token)
                    decoder_input = predicted_token

                    # Stop if all sequences have predicted EOS
                    if (predicted_token == hindi_vocab['<eos>']).all():
                        break

                predicted_tokens = torch.stack(predicted_tokens).T

            else:  # Transformer
                max_len = 50  # Maximum length limit
                batch_size = src.size(0)
                predicted_tokens = torch.ones(batch_size, 1).fill_(hindi_vocab['<sos>']).long().to(device)

                for _ in range(max_len):
                    trg_mask = model.transformer.generate_square_subsequent_mask(predicted_tokens.size(1)).to(device)
                    output = model(
                        src,
                        predicted_tokens,
                        src_key_padding_mask=(src == 0),
                        tgt_mask=trg_mask,
                        tgt_key_padding_mask=(predicted_tokens == 0)
                    )
                    next_token = output.argmax(2)[:, -1].unsqueeze(1)
                    predicted_tokens = torch.cat([predicted_tokens, next_token], dim=1)

                    # Stop if all sequences have predicted EOS
                    if (next_token.squeeze(1) == hindi_vocab['<eos>']).all():
                        break

            # Get a few examples
            for i in range(min(num_samples, src.size(0))):
                # Source sentence (English)
                src_tokens = [reverse_english_vocab.get(idx.item(), '<unk>') for idx in src[i] if idx.item() != 0]

                # Reference translation (Hindi)
                ref_tokens = [reverse_hindi_vocab.get(idx.item(), '<unk>') for idx in trg[i] if idx.item() not in [0, hindi_vocab['<sos>'], hindi_vocab['<eos>']]]

                # Model prediction (Hindi)
                pred_tokens = [reverse_hindi_vocab.get(idx.item(), '<unk>') for idx in predicted_tokens[i] if idx.item() not in [0, hindi_vocab['<sos>'], hindi_vocab['<eos>']]]

                samples.append({
                    'source': ' '.join(src_tokens),
                    'reference': ' '.join(ref_tokens),
                    'prediction': ' '.join(pred_tokens)
                })

                if len(samples) >= num_samples:
                    break

            if len(samples) >= num_samples:
                break

    print(f"\n===== {model_type.upper()} MODEL TRANSLATIONS =====")
    for i, sample in enumerate(samples):
        print(f"\nExample {i+1}:")
        print(f"Source (English): {sample['source']}")
        print(f"Reference (Hindi): {sample['reference']}")
        print(f"Prediction (Hindi): {sample['prediction']}")

    return samples

# Add an improved model that combines LSTM and Transformer architectures
class HybridLSTMTransformerModel(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model=512, nhead=8,
                 num_encoder_layers=3, num_decoder_layers=3, dim_feedforward=2048,
                 dropout=0.1, lstm_hidden_dim=512, lstm_layers=2):
        super(HybridLSTMTransformerModel, self).__init__()

        # Embedding layers
        self.src_embedding = nn.Embedding(src_vocab_size, d_model)
        self.tgt_embedding = nn.Embedding(tgt_vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(d_model)

        # LSTM layers for encoding context
        self.encoder_lstm = nn.LSTM(
            d_model,
            lstm_hidden_dim,
            lstm_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # Linear layer to project LSTM output to transformer dimension
        self.lstm_to_transformer = nn.Linear(lstm_hidden_dim * 2, d_model)

        # Transformer encoder-decoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_encoder_layers
        )

        decoder_layer = nn.TransformerDecoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True
        )
        self.transformer_decoder = nn.TransformerDecoder(
            decoder_layer,
            num_decoder_layers
        )

        # Output layer
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

        # Residual connection weight (learnable parameter)
        self.alpha = nn.Parameter(torch.FloatTensor([0.5]))

    def generate_square_subsequent_mask(self, sz):
        mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
        mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
        return mask

    def forward(self, src, tgt, src_key_padding_mask=None, tgt_key_padding_mask=None):
        # Embed source and target sequences
        src_embedded = self.positional_encoding(self.src_embedding(src))
        tgt_embedded = self.positional_encoding(self.tgt_embedding(tgt))

        # Pass source through LSTM
        lstm_output, _ = self.encoder_lstm(src_embedded)
        lstm_output = self.lstm_to_transformer(lstm_output)

        # Transformer encoder
        transformer_memory = self.transformer_encoder(
            lstm_output,
            src_key_padding_mask=src_key_padding_mask
        )

        # Add residual connection from LSTM output to transformer encoder output
        transformer_memory = self.alpha * transformer_memory + (1 - self.alpha) * lstm_output

        # Create mask for transformer decoder
        tgt_mask = self.generate_square_subsequent_mask(tgt.size(1)).to(tgt.device)

        # Transformer decoder
        output = self.transformer_decoder(
            tgt_embedded,
            transformer_memory,
            tgt_mask=tgt_mask,
            tgt_key_padding_mask=tgt_key_padding_mask
        )

        # Final output projection
        return self.fc_out(output)

def run_lstm_ablation(train_dataset, train_loader, test_loader, device, reverse_hindi_vocab, reverse_english_vocab):
    results = {}

    # Base LSTM configuration
    base_lstm_config = {
        'model_type': 'lstm',
        'embedding_dim': 300,
        'hidden_dim': 512,
        'num_layers': 2,
        'dropout': 0.2,
        'epochs': 5
    }

    # LSTM variations
    lstm_variations = [
        {'name': 'base', 'config': base_lstm_config.copy()},
        {'name': 'reduced_layers', 'config': {**base_lstm_config, 'num_layers': 1}},
        {'name': 'increased_layers', 'config': {**base_lstm_config, 'num_layers': 3}},
        {'name': 'reduced_hidden', 'config': {**base_lstm_config, 'hidden_dim': 256}},
        {'name': 'increased_hidden', 'config': {**base_lstm_config, 'hidden_dim': 768}},
        {'name': 'increased_dropout', 'config': {**base_lstm_config, 'dropout': 0.4}}
    ]

    print("Starting LSTM Ablation Study...")
    for variation in lstm_variations:
        try:
            print(f"\nTesting LSTM configuration: {variation['name']}")
            config = variation['config']

            # Initialize model
            lstm_encoder = LSTMEncoder(
                vocab_size=len(train_dataset.english_vocab),
                embedding_dim=config['embedding_dim'],
                hidden_dim=config['hidden_dim'],
                num_layers=config['num_layers'],
                dropout=config['dropout']
            ).to(device)

            lstm_decoder = LSTMDecoder(
                vocab_size=len(train_dataset.hindi_vocab),
                embedding_dim=config['embedding_dim'],
                hidden_dim=config['hidden_dim'],
                num_layers=config['num_layers'],
                dropout=config['dropout']
            ).to(device)

            lstm_model = LSTMSeq2SeqModel(lstm_encoder, lstm_decoder).to(device)
            criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
            optimizer = optim.Adam(lstm_model.parameters(), lr=0.001)

            # Training loop
            start_time = time.time()
            train_losses = []
            for epoch in range(config['epochs']):
                loss = train_model(lstm_model, train_loader, criterion, optimizer, device, model_type='lstm')
                train_losses.append(loss)
                print(f'Epoch [{epoch+1}/{config["epochs"]}], Loss: {loss:.4f}')

            training_time = time.time() - start_time

            # Evaluation
            bleu = evaluate_model(
                lstm_model,
                test_loader,
                device,
                train_dataset.hindi_vocab,
                train_dataset.english_vocab,
                model_type='lstm'
            )

            # Store results
            results[f'lstm_{variation["name"]}'] = {
                'config': config,
                'train_losses': train_losses,
                'bleu': bleu,
                'training_time': training_time
            }

            print(f"BLEU Score: {bleu}, Training time: {training_time:.2f}s")

            # Get sample translations
            samples = display_sample_translations(
                lstm_model,
                test_loader,
                device,
                train_dataset.hindi_vocab,
                reverse_hindi_vocab,
                reverse_english_vocab,
                model_type='lstm',
                num_samples=2
            )

        except Exception as e:
            print(f"Error in LSTM variation {variation['name']}: {str(e)}")
            print("Skipping to next variation...")
            continue

    return results

def run_transformer_ablation(train_dataset, train_loader, test_loader, device, reverse_hindi_vocab, reverse_english_vocab):
    results = {}

    # Base Transformer configuration
    base_transformer_config = {
        'model_type': 'transformer',
        'embedding_dim': 512,
        'nhead': 8,
        'num_encoder_layers': 6,
        'num_decoder_layers': 6,
        'dim_feedforward': 2048,
        'dropout': 0.1,
        'epochs': 5
    }

    # Transformer variations
    transformer_variations = [
        {'name': 'base', 'config': base_transformer_config.copy()},
        {'name': 'reduced_layers', 'config': {**base_transformer_config, 'num_encoder_layers': 3, 'num_decoder_layers': 3}},
        {'name': 'reduced_heads', 'config': {**base_transformer_config, 'nhead': 4}},
        {'name': 'increased_heads', 'config': {**base_transformer_config, 'nhead': 16, 'embedding_dim': 512}},
        {'name': 'reduced_feedforward', 'config': {**base_transformer_config, 'dim_feedforward': 1024}},
        {'name': 'increased_dropout', 'config': {**base_transformer_config, 'dropout': 0.3}}
    ]

    print("\nStarting Transformer Ablation Study...")
    for variation in transformer_variations:
        try:
            print(f"\nTesting Transformer configuration: {variation['name']}")
            config = variation['config']

            # Initialize model
            transformer_model = TransformerModel(
                src_vocab_size=len(train_dataset.english_vocab),
                tgt_vocab_size=len(train_dataset.hindi_vocab),
                d_model=config['embedding_dim'],
                nhead=config['nhead'],
                num_encoder_layers=config['num_encoder_layers'],
                num_decoder_layers=config['num_decoder_layers'],
                dim_feedforward=config['dim_feedforward'],
                dropout=config['dropout']
            ).to(device)

            criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
            optimizer = optim.Adam(transformer_model.parameters(), lr=0.001)

            # Training loop
            start_time = time.time()
            train_losses = []
            for epoch in range(config['epochs']):
                loss = train_model(transformer_model, train_loader, criterion, optimizer, device, model_type='transformer')
                train_losses.append(loss)
                print(f'Epoch [{epoch+1}/{config["epochs"]}], Loss: {loss:.4f}')

            training_time = time.time() - start_time

            # Evaluation
            bleu = evaluate_model(
                transformer_model,
                test_loader,
                device,
                train_dataset.hindi_vocab,
                train_dataset.english_vocab,
                model_type='transformer'
            )

            # Store results
            results[f'transformer_{variation["name"]}'] = {
                'config': config,
                'train_losses': train_losses,
                'bleu': bleu,
                'training_time': training_time
            }

            print(f"BLEU Score: {bleu}, Training time: {training_time:.2f}s")

            # Get sample translations
            samples = display_sample_translations(
                transformer_model,
                test_loader,
                device,
                train_dataset.hindi_vocab,
                reverse_hindi_vocab,
                reverse_english_vocab,
                model_type='transformer',
                num_samples=2
            )

        except Exception as e:
            print(f"Error in Transformer variation {variation['name']}: {str(e)}")
            print("Skipping to next variation...")
            continue

    return results

def run_hybrid_ablation(train_dataset, train_loader, test_loader, device, reverse_hindi_vocab, reverse_english_vocab):
    results = {}

    # Base Hybrid configuration
    base_hybrid_config = {
        'model_type': 'hybrid',
        'embedding_dim': 512,
        'nhead': 8,
        'num_encoder_layers': 3,
        'num_decoder_layers': 3,
        'dim_feedforward': 2048,
        'dropout': 0.1,
        'lstm_hidden_dim': 512,
        'lstm_layers': 2,
        'epochs': 5
    }

    # Hybrid variations
    hybrid_variations = [
        {'name': 'base', 'config': base_hybrid_config.copy()},
        {'name': 'balanced', 'config': {**base_hybrid_config, 'num_encoder_layers': 2, 'num_decoder_layers': 2, 'lstm_layers': 2}},
        {'name': 'lstm_heavy', 'config': {**base_hybrid_config, 'lstm_layers': 3, 'lstm_hidden_dim': 768, 'num_encoder_layers': 1, 'num_decoder_layers': 1}},
        {'name': 'transformer_heavy', 'config': {**base_hybrid_config, 'lstm_layers': 1, 'num_encoder_layers': 4, 'num_decoder_layers': 4}}
    ]

    print("\nStarting Hybrid Model Ablation Study...")
    for variation in hybrid_variations:
        try:
            print(f"\nTesting Hybrid configuration: {variation['name']}")
            config = variation['config']

            # Initialize model
            hybrid_model = HybridLSTMTransformerModel(
                src_vocab_size=len(train_dataset.english_vocab),
                tgt_vocab_size=len(train_dataset.hindi_vocab),
                d_model=config['embedding_dim'],
                nhead=config['nhead'],
                num_encoder_layers=config['num_encoder_layers'],
                num_decoder_layers=config['num_decoder_layers'],
                dim_feedforward=config['dim_feedforward'],
                dropout=config['dropout'],
                lstm_hidden_dim=config['lstm_hidden_dim'],
                lstm_layers=config['lstm_layers']
            ).to(device)

            criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
            optimizer = optim.Adam(hybrid_model.parameters(), lr=0.001)

            # Training loop
            start_time = time.time()
            train_losses = []
            for epoch in range(config['epochs']):
                loss = train_hybrid_model(hybrid_model, train_loader, criterion, optimizer, device)
                train_losses.append(loss)
                print(f'Epoch [{epoch+1}/{config["epochs"]}], Loss: {loss:.4f}')

            training_time = time.time() - start_time

            # Evaluation
            bleu = evaluate_hybrid_model(
                hybrid_model,
                test_loader,
                device,
                train_dataset.hindi_vocab
            )

            # Store results
            results[f'hybrid_{variation["name"]}'] = {
                'config': config,
                'train_losses': train_losses,
                'bleu': bleu,
                'training_time': training_time
            }

            print(f"BLEU Score: {bleu}, Training time: {training_time:.2f}s")

            # Get sample translations
            samples = display_hybrid_translations(
                hybrid_model,
                test_loader,
                device,
                train_dataset.hindi_vocab,
                reverse_hindi_vocab,
                reverse_english_vocab,
                num_samples=2
            )

        except Exception as e:
            print(f"Error in Hybrid variation {variation['name']}: {str(e)}")
            print("Skipping to next variation...")
            continue

    return results

def train_hybrid_model(model, train_loader, criterion, optimizer, device):
    model.train()
    total_loss = 0

    for batch in train_loader:
        src = batch['english'].to(device)
        trg = batch['hindi'].to(device)

        # Use teacher forcing: decoder input is trg[:-1], target is trg[1:]
        trg_input = trg[:, :-1]
        trg_target = trg[:, 1:]

        # Create padding masks
        src_padding_mask = (src == 0)
        trg_padding_mask = (trg_input == 0)

        optimizer.zero_grad()

        outputs = model(
            src,
            trg_input,
            src_key_padding_mask=src_padding_mask,
            tgt_key_padding_mask=trg_padding_mask
        )

        # Reshape for loss calculation
        outputs = outputs.reshape(-1, outputs.shape[-1])
        trg_target = trg_target.reshape(-1)

        loss = criterion(outputs, trg_target)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1)
        optimizer.step()
        total_loss += loss.item()

    return total_loss / len(train_loader)

def evaluate_hybrid_model(model, test_loader, device, hindi_vocab):
    model.eval()
    references = []
    hypotheses = []

    with torch.no_grad():
        for batch in test_loader:
            src = batch['english'].to(device)
            trg = batch['hindi'].to(device)

            # Generate translations
            max_len = trg.shape[1] - 1
            batch_size = src.size(0)
            predicted_tokens = torch.ones(batch_size, 1).fill_(hindi_vocab['<sos>']).long().to(device)

            for _ in range(max_len):
                # Create padding mask
                src_padding_mask = (src == 0)
                tgt_padding_mask = (predicted_tokens == 0)

                # Get next token predictions
                output = model(
                    src,
                    predicted_tokens,
                    src_key_padding_mask=src_padding_mask,
                    tgt_key_padding_mask=tgt_padding_mask
                )

                # Select token with highest probability
                next_token = output[:, -1, :].argmax(1).unsqueeze(1)
                predicted_tokens = torch.cat([predicted_tokens, next_token], dim=1)

                # Stop if all sequences have predicted EOS
                if (next_token.squeeze(1) == hindi_vocab['<eos>']).all():
                    break

            # Format references and hypotheses for BLEU calculation
            for i in range(src.shape[0]):
                ref_tokens = [hindi_vocab.get(idx.item(), '<unk>') for idx in trg[i, 1:] if idx.item() != 0]
                hyp_tokens = [hindi_vocab.get(idx.item(), '<unk>') for idx in predicted_tokens[i, 1:] if idx.item() not in [0, hindi_vocab['<eos>']]]
                references.append([ref_tokens])  # Each reference is a list of tokens
                hypotheses.append(hyp_tokens)

    # Calculate BLEU score
    bleu = corpus_bleu(references, hypotheses)
    return bleu

def display_hybrid_translations(model, test_loader, device, hindi_vocab, reverse_hindi_vocab, reverse_english_vocab, num_samples=5):
    model.eval()
    samples = []

    with torch.no_grad():
        for batch in test_loader:
            src = batch['english'].to(device)
            trg = batch['hindi'].to(device)

            # Generate translations
            max_len = 50  # Maximum length limit
            batch_size = src.size(0)
            predicted_tokens = torch.ones(batch_size, 1).fill_(hindi_vocab['<sos>']).long().to(device)

            for _ in range(max_len):
                # Create padding mask
                src_padding_mask = (src == 0)
                tgt_padding_mask = (predicted_tokens == 0)

                # Get next token predictions
                output = model(
                    src,
                    predicted_tokens,
                    src_key_padding_mask=src_padding_mask,
                    tgt_key_padding_mask=tgt_padding_mask
                )

                # Select token with highest probability
                next_token = output[:, -1, :].argmax(1).unsqueeze(1)
                predicted_tokens = torch.cat([predicted_tokens, next_token], dim=1)

                # Stop if all sequences have predicted EOS
                if (next_token.squeeze(1) == hindi_vocab['<eos>']).all():
                    break

            # Get a few examples
            for i in range(min(num_samples, src.size(0))):
                # Source sentence (English)
                src_tokens = [reverse_english_vocab.get(idx.item(), '<unk>') for idx in src[i] if idx.item() != 0]

                # Reference translation (Hindi)
                ref_tokens = [reverse_hindi_vocab.get(idx.item(), '<unk>') for idx in trg[i] if idx.item() not in [0, hindi_vocab['<sos>'], hindi_vocab['<eos>']]]

                # Model prediction (Hindi)
                pred_tokens = [reverse_hindi_vocab.get(idx.item(), '<unk>') for idx in predicted_tokens[i] if idx.item() not in [0, hindi_vocab['<sos>'], hindi_vocab['<eos>']]]

                samples.append({
                    'source': ' '.join(src_tokens),
                    'reference': ' '.join(ref_tokens),
                    'prediction': ' '.join(pred_tokens)
                })

                if len(samples) >= num_samples:
                    break

            if len(samples) >= num_samples:
                break

    print(f"\n===== HYBRID MODEL TRANSLATIONS =====")
    for i, sample in enumerate(samples):
        print(f"\nExample {i+1}:")
        print(f"Source (English): {sample['source']}")
        print(f"Reference (Hindi): {sample['reference']}")
        print(f"Prediction (Hindi): {sample['prediction']}")

    return samples

def visualize_ablation_results(results):
    import matplotlib.pyplot as plt

    # Extract model types and variants
    model_types = set()
    for key in results.keys():
        model_type = key.split('_')[0]
        model_types.add(model_type)

    # Plot BLEU scores
    plt.figure(figsize=(15, 8))

    for model_type in model_types:
        variant_names = []
        bleu_scores = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                variant_names.append(variant)
                bleu_scores.append(value['bleu'])

        plt.bar(
            [f"{model_type}_{name}" for name in variant_names],
            bleu_scores,
            alpha=0.7,
            label=f"{model_type.capitalize()} Variants"
        )

    plt.xlabel('Model Configuration')
    plt.ylabel('BLEU Score')
    plt.title('BLEU Scores Across Model Variants')
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # Plot training time
    plt.figure(figsize=(15, 8))

    for model_type in model_types:
        variant_names = []
        training_times = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                variant_names.append(variant)
                training_times.append(value['training_time'])

        plt.bar(
            [f"{model_type}_{name}" for name in variant_names],
            training_times,
            alpha=0.7,
            label=f"{model_type.capitalize()} Variants"
        )

    plt.xlabel('Model Configuration')
    plt.ylabel('Training Time (seconds)')
    plt.title('Training Time Across Model Variants')
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # Plot final training loss
    plt.figure(figsize=(15, 8))

    for model_type in model_types:
        variant_names = []
        final_losses = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                variant_names.append(variant)
                final_losses.append(value['train_losses'][-1])

        plt.bar(
            [f"{model_type}_{name}" for name in variant_names],
            final_losses,
            alpha=0.7,
            label=f"{model_type.capitalize()} Variants"
        )

    plt.xlabel('Model Configuration')
    plt.ylabel('Final Training Loss')
    plt.title('Final Training Loss Across Model Variants')
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

def visualize_ablation_results(results):
    import matplotlib.pyplot as plt
    import seaborn as sns
    import numpy as np

    # Set style for better visualizations
    plt.style.use('seaborn')
    sns.set_palette("husl")

    # 1. BLEU Scores Comparison
    plt.figure(figsize=(15, 8))
    model_types = ['lstm', 'transformer', 'hybrid']

    for model_type in model_types:
        variant_names = []
        bleu_scores = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                variant_names.append(variant)
                bleu_scores.append(value['bleu'])

        x = np.arange(len(variant_names))
        width = 0.25

        plt.bar(x + model_types.index(model_type)*width, bleu_scores, width,
                label=f"{model_type.capitalize()}", alpha=0.7)

    plt.xlabel('Model Variants')
    plt.ylabel('BLEU Score')
    plt.title('BLEU Scores Comparison Across Model Types')
    plt.xticks(x + width, variant_names, rotation=45)
    plt.legend()
    plt.tight_layout()
    plt.show()

    # 2. Learning Curves
    plt.figure(figsize=(15, 8))
    for model_type in model_types:
        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                plt.plot(value['train_losses'],
                        label=f"{model_type.capitalize()}-{variant}",
                        alpha=0.7)

    plt.xlabel('Epochs')
    plt.ylabel('Training Loss')
    plt.title('Learning Curves for All Model Variants')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # 3. Training Time vs BLEU Score
    plt.figure(figsize=(15, 8))
    for model_type in model_types:
        times = []
        scores = []
        names = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                times.append(value['training_time'])
                scores.append(value['bleu'])
                names.append(variant)

        plt.scatter(times, scores, s=100, label=model_type.capitalize())
        for i, name in enumerate(names):
            plt.annotate(name, (times[i], scores[i]))

    plt.xlabel('Training Time (seconds)')
    plt.ylabel('BLEU Score')
    plt.title('Training Time vs BLEU Score')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # 4. Model Architecture Comparison
    plt.figure(figsize=(15, 8))
    model_complexities = []
    model_names = []

    for model_type in model_types:
        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                config = value['config']

                # Calculate approximate model complexity
                if model_type == 'lstm':
                    complexity = (config['embedding_dim'] * config['hidden_dim'] *
                                config['num_layers'] * 2)  # Bi-directional
                elif model_type == 'transformer':
                    complexity = (config['embedding_dim'] * config['nhead'] *
                                config['num_encoder_layers'] * config['dim_feedforward'])
                else:  # hybrid
                    complexity = (config['embedding_dim'] * config['lstm_hidden_dim'] *
                                config['lstm_layers'] * 2 +  # LSTM part
                                config['embedding_dim'] * config['nhead'] *
                                config['num_encoder_layers'] * config['dim_feedforward'])  # Transformer part

                model_complexities.append(complexity)
                model_names.append(f"{model_type}-{variant}")

    plt.bar(model_names, model_complexities, alpha=0.7)
    plt.xlabel('Model Variants')
    plt.ylabel('Approximate Model Complexity')
    plt.title('Model Architecture Complexity Comparison')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # 5. Performance Heatmap
    plt.figure(figsize=(15, 8))
    metrics = ['bleu', 'training_time', 'train_losses']
    model_variants = [key for key in results.keys()]

    performance_matrix = np.zeros((len(metrics), len(model_variants)))

    for i, metric in enumerate(metrics):
        for j, variant in enumerate(model_variants):
            if metric == 'train_losses':
                performance_matrix[i, j] = results[variant][metric][-1]
            else:
                performance_matrix[i, j] = results[variant][metric]

    # Normalize the matrix
    performance_matrix = (performance_matrix - performance_matrix.min()) / (performance_matrix.max() - performance_matrix.min())

    sns.heatmap(performance_matrix,
                xticklabels=model_variants,
                yticklabels=metrics,
                cmap='YlOrRd',
                annot=True,
                fmt='.2f')

    plt.title('Normalized Performance Metrics Heatmap')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # 6. Convergence Analysis
    plt.figure(figsize=(15, 8))
    for model_type in model_types:
        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                losses = value['train_losses']
                convergence_rate = np.diff(losses) / losses[:-1]
                plt.plot(convergence_rate,
                        label=f"{model_type.capitalize()}-{variant}",
                        alpha=0.7)

    plt.xlabel('Epochs')
    plt.ylabel('Convergence Rate')
    plt.title('Convergence Rate Analysis')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # 7. Model Efficiency Analysis
    plt.figure(figsize=(15, 8))
    for model_type in model_types:
        efficiencies = []
        variants = []

        for key, value in results.items():
            if key.startswith(f"{model_type}_"):
                variant = key[len(model_type)+1:]
                # Calculate efficiency as BLEU score per training time
                efficiency = value['bleu'] / value['training_time']
                efficiencies.append(efficiency)
                variants.append(variant)

        plt.bar([f"{model_type}-{v}" for v in variants], efficiencies, alpha=0.7)

    plt.xlabel('Model Variants')
    plt.ylabel('Efficiency (BLEU Score / Training Time)')
    plt.title('Model Efficiency Analysis')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

def main():
    train_dataset = NMTDataset(
        '/kaggle/input/neuralmachinetranslation/english.train', '/kaggle/input/neuralmachinetranslation/hindi.train'
    )
    test_dataset = NMTDataset(
        '/kaggle/input/neuralmachinetranslation/english.test', '/kaggle/input/neuralmachinetranslation/hindi.test',
        english_vocab=train_dataset.english_vocab,
        hindi_vocab=train_dataset.hindi_vocab
    )

    BATCH_SIZE = 64
    EMBEDDING_DIM = 300
    HIDDEN_DIM = 512
    NUM_LAYERS = 2
    LEARNING_RATE = 0.001
    NUM_EPOCHS = 15

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn)

    # Create reverse vocabularies for display
    reverse_english_vocab = {idx: token for token, idx in train_dataset.english_vocab.items()}
    reverse_hindi_vocab = {idx: token for token, idx in train_dataset.hindi_vocab.items()}

    # Run ablation studies separately
    print("\n=== Starting LSTM Ablation Study ===")
    lstm_results = run_lstm_ablation(
        train_dataset,
        train_loader,
        test_loader,
        device,
        reverse_hindi_vocab,
        reverse_english_vocab
    )

    print("\n=== Starting Transformer Ablation Study ===")
    transformer_results = run_transformer_ablation(
        train_dataset,
        train_loader,
        test_loader,
        device,
        reverse_hindi_vocab,
        reverse_english_vocab
    )

    print("\n=== Starting Hybrid Model Ablation Study ===")
    hybrid_results = run_hybrid_ablation(
        train_dataset,
        train_loader,
        test_loader,
        device,
        reverse_hindi_vocab,
        reverse_english_vocab
    )

    # Combine all results
    all_results = {**lstm_results, **transformer_results, **hybrid_results}

    # Visualize results
    visualize_ablation_results(all_results)

    # Train the best model based on ablation results
    print("\nTraining the best model configuration...")
    best_model_type = max(all_results.items(), key=lambda x: x[1]['bleu'])[0].split('_')[0]
    best_variant = max(all_results.items(), key=lambda x: x[1]['bleu'])[0].split('_')[1]

    if best_model_type == 'lstm':
        best_config = lstm_results[f'lstm_{best_variant}']['config']
        best_model = LSTMSeq2SeqModel(
            LSTMEncoder(
                vocab_size=len(train_dataset.english_vocab),
                embedding_dim=best_config['embedding_dim'],
                hidden_dim=best_config['hidden_dim'],
                num_layers=best_config['num_layers'],
                dropout=best_config['dropout']
            ),
            LSTMDecoder(
                vocab_size=len(train_dataset.hindi_vocab),
                embedding_dim=best_config['embedding_dim'],
                hidden_dim=best_config['hidden_dim'],
                num_layers=best_config['num_layers'],
                dropout=best_config['dropout']
            )
        ).to(device)

        criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
        optimizer = optim.Adam(best_model.parameters(), lr=LEARNING_RATE)

        for epoch in range(NUM_EPOCHS):
            loss = train_model(best_model, train_loader, criterion, optimizer, device, model_type='lstm')
            print(f'Best LSTM Model Epoch [{epoch+1}/{NUM_EPOCHS}], Loss: {loss:.4f}')

    elif best_model_type == 'transformer':
        best_config = transformer_results[f'transformer_{best_variant}']['config']
        best_model = TransformerModel(
            src_vocab_size=len(train_dataset.english_vocab),
            tgt_vocab_size=len(train_dataset.hindi_vocab),
            d_model=best_config['embedding_dim'],
            nhead=best_config['nhead'],
            num_encoder_layers=best_config['num_encoder_layers'],
            num_decoder_layers=best_config['num_decoder_layers'],
            dim_feedforward=best_config['dim_feedforward'],
            dropout=best_config['dropout']
        ).to(device)

        criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
        optimizer = optim.Adam(best_model.parameters(), lr=LEARNING_RATE)

        for epoch in range(NUM_EPOCHS):
            loss = train_model(best_model, train_loader, criterion, optimizer, device, model_type='transformer')
            print(f'Best Transformer Model Epoch [{epoch+1}/{NUM_EPOCHS}], Loss: {loss:.4f}')

    else:  # hybrid
        best_config = hybrid_results[f'hybrid_{best_variant}']['config']
        best_model = HybridLSTMTransformerModel(
            src_vocab_size=len(train_dataset.english_vocab),
            tgt_vocab_size=len(train_dataset.hindi_vocab),
            d_model=best_config['embedding_dim'],
            nhead=best_config['nhead'],
            num_encoder_layers=best_config['num_encoder_layers'],
            num_decoder_layers=best_config['num_decoder_layers'],
            dim_feedforward=best_config['dim_feedforward'],
            dropout=best_config['dropout'],
            lstm_hidden_dim=best_config['lstm_hidden_dim'],
            lstm_layers=best_config['lstm_layers']
        ).to(device)

        criterion = nn.CrossEntropyLoss(ignore_index=train_dataset.english_vocab['<pad>'])
        optimizer = optim.Adam(best_model.parameters(), lr=LEARNING_RATE)

        for epoch in range(NUM_EPOCHS):
            loss = train_hybrid_model(best_model, train_loader, criterion, optimizer, device)
            print(f'Best Hybrid Model Epoch [{epoch+1}/{NUM_EPOCHS}], Loss: {loss:.4f}')

    # Save the best model
    torch.save(best_model.state_dict(), f'best_{best_model_type}_nmt_model.pth')
    print(f"\nBest model saved as 'best_{best_model_type}_nmt_model.pth'")

if __name__ == "__main__":
    main()

"""# Mathematical Analysis of Hybrid Model

The hybrid LSTM-Transformer model combines the strengths of both architectures:

1. LSTMs excel at capturing sequential dependencies and handling variable-length inputs
2. Transformers excel at modeling long-range dependencies through self-attention mechanisms

## Mathematical formulation:

For an input sequence X = [x₁, x₂, ..., xₙ] and a target sequence Y = [y₁, y₂, ..., yₘ]:

### LSTM Component:
The bidirectional LSTM processes input embeddings to produce contextual representations:

H_lstm = BiLSTM(Embedding(X))

Where H_lstm ∈ ℝⁿˣ²ᵈ (n is sequence length, d is hidden dimension)

### Transformer Component:
The transformer encoder further processes these contextual representations:

H_transformer = TransformerEncoder(Linear(H_lstm))

Where H_transformer ∈ ℝⁿˣᵈ_model

### Residual Connection:
The hybrid model uses a learned parameter α to combine LSTM and Transformer representations:

H_hybrid = α·H_transformer + (1-α)·Linear(H_lstm)

This adaptive weighting allows the model to determine how much to rely on each component.

### Decoder:
The decoder uses standard transformer decoder architecture with the hybrid encoded representation:

Output = TransformerDecoder(Embedding(Y), H_hybrid)

### Theoretical Advantages:

1. **Complementary strengths**: LSTMs capture local dependencies while transformers capture global patterns
2. **Adaptive weighting**: The α parameter learns the optimal balance between LSTM and transformer representations
3. **Enhanced representation**: The LSTM pre-processes the input, helping the transformer focus on higher-level patterns
4. **Improved gradient flow**: The residual connection helps address vanishing gradient issues

This hybrid approach theoretically should outperform both standalone LSTM and Transformer models.

"""

# Visualization section
import matplotlib.pyplot as plt

# Plot the LSTM training loss
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(range(1, len(train_losses_lstm) + 1), train_losses_lstm, marker='o', linestyle='-', color='b')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('LSTM Training Loss')
plt.grid(True)

# Plot the Transformer training loss
plt.subplot(1, 2, 2)
plt.plot(range(1, len(train_losses_transformer) + 1), train_losses_transformer, marker='o', linestyle='-', color='r')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Transformer Training Loss')
plt.grid(True)

plt.tight_layout()
plt.show()

# Combined plot for comparison
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(train_losses_lstm) + 1), train_losses_lstm, marker='o', linestyle='-', color='b', label='LSTM')
plt.plot(range(1, len(train_losses_transformer) + 1), train_losses_transformer, marker='x', linestyle='--', color='r', label='Transformer')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training Loss Comparison')
plt.legend()
plt.grid(True)
plt.show()

"""# Test Bi-LSTM(Discarded due to low perfomance)"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

def tokenize_document(document):
    # Split document into sentences
    sentences = sent_tokenize(document)

    # Preprocess each sentence
    processed_sentences = [preprocess_text(sentence) for sentence in sentences]

    # Remove empty sentences
    processed_sentences = [s for s in processed_sentences if s.strip()]

    return processed_sentences

# Apply preprocessing to the sampled data
train_sample['processed_article'] = train_sample['article'].apply(tokenize_document)
train_sample['processed_highlights'] = train_sample['highlights'].apply(tokenize_document)

# Create labels for extractive summarization (1 if sentence is in highlights, 0 otherwise)
def create_extractive_labels(article_sentences, highlight_sentences):
    labels = []
    for sentence in article_sentences:
        # Check if this sentence is similar to any highlight sentence
        is_in_highlights = any(
            similarity_score(sentence, highlight) > 0.7
            for highlight in highlight_sentences
        )
        labels.append(1 if is_in_highlights else 0)
    return labels

def similarity_score(sent1, sent2):
    # Simple word overlap similarity
    words1 = set(word_tokenize(sent1))
    words2 = set(word_tokenize(sent2))

    if not words1 or not words2:
        return 0

    overlap = len(words1.intersection(words2))
    return overlap / max(len(words1), len(words2))

# Create extractive labels
train_sample['extractive_labels'] = [
    create_extractive_labels(article, highlight)
    for article, highlight in zip(train_sample['processed_article'], train_sample['processed_highlights'])
]

from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, TrainingArguments, Trainer, EarlyStoppingCallback,TrainerCallback
import torch.nn as nn
import torch.nn.functional as F

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Define BiLSTM model architecture
class BiLSTMSeq2Seq(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers=1, dropout=0.1):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.num_layers = num_layers

        # Encoder (BiLSTM)
        self.encoder = nn.LSTM(embedding_dim, hidden_dim,
                             bidirectional=True, batch_first=True, num_layers=num_layers,
                             dropout=dropout if num_layers > 1 else 0)

        # Decoder (LSTM with attention)
        self.decoder = nn.LSTM(embedding_dim + hidden_dim*2, hidden_dim*2,  # Attention concatenation
                             batch_first=True, dropout=dropout, num_layers=1)

        # Attention mechanism
        self.attention = nn.Linear(hidden_dim*2 + hidden_dim*2, hidden_dim*2)
        self.v = nn.Linear(hidden_dim*2, 1, bias=False)

        # Final projection layer
        self.fc = nn.Linear(hidden_dim*2, vocab_size)

        # Dropout layers
        self.dropout = nn.Dropout(dropout)

    def forward(self, src, trg=None, max_len=128, teacher_forcing_ratio=0.5):
        batch_size = src.size(0)

        # Encoder Forward Pass
        embedded = self.dropout(self.embedding(src))
        encoder_outputs, (hidden, cell) = self.encoder(embedded)

        # Prepare decoder initial states
        hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1).unsqueeze(0)
        cell = torch.cat((cell[-2,:,:], cell[-1,:,:]), dim=1).unsqueeze(0)

        # Decoder Setup
        if trg is None:
            trg = torch.zeros((batch_size, max_len), dtype=torch.long, device=src.device)
            trg[:,0] = 1  # Start with SOS token

        decoder_input = self.embedding(trg[:,0].unsqueeze(1))
        outputs = torch.zeros(max_len, batch_size, self.fc.out_features, device=src.device)

        # Decoding Loop
        for t in range(1, max_len):
            # Attention Calculation
            energy = torch.tanh(self.attention(torch.cat((
                hidden.repeat(encoder_outputs.size(1), 1, 1).permute(1,0,2),
                encoder_outputs
            ), dim=2)))

            attention = F.softmax(self.v(energy).squeeze(2), dim=1)
            context = torch.bmm(attention.unsqueeze(1), encoder_outputs)

            # Decoder Step
            decoder_output, (hidden, cell) = self.decoder(
                torch.cat((decoder_input, context), dim=2),
                (hidden, cell)
            )

            # Project to vocabulary space
            output = self.fc(decoder_output.squeeze(1))
            outputs[t] = output

            # Teacher Forcing
            use_teacher_forcing = random.random() < teacher_forcing_ratio
            top1 = output.argmax(1)

            decoder_input = self.embedding(trg[:,t].unsqueeze(1) if use_teacher_forcing else top1.unsqueeze(1))
            decoder_input = self.dropout(decoder_input)

        return outputs.permute(1, 0, 2)

    def generate(self, src, max_len=128, temperature=1.0):
        with torch.no_grad():
            # Encoder forward pass
            encoder_outputs, (hidden, cell) = self.encoder(self.embedding(src))

            # Prepare decoder initial states
            hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1).unsqueeze(0)
            cell = torch.cat((cell[-2,:,:], cell[-1,:,:]), dim=1).unsqueeze(0)

            outputs = []
            decoder_input = torch.tensor([[1]], device=src.device)  # SOS token

            for _ in range(max_len):
                decoder_emb = self.embedding(decoder_input)

                # Attention
                energy = torch.tanh(self.attention(torch.cat((
                    hidden.repeat(encoder_outputs.size(1), 1, 1).permute(1,0,2),
                    encoder_outputs
                ), dim=2)))

                attention = F.softmax(self.v(energy).squeeze(2), dim=1)
                context = torch.bmm(attention.unsqueeze(1), encoder_outputs)

                # Decoder step
                decoder_output, (hidden, cell) = self.decoder(
                    torch.cat((decoder_emb, context), dim=2),
                    (hidden, cell)
                )

                # Output projection
                logits = self.fc(decoder_output.squeeze(1)) / temperature
                probabilities = F.softmax(logits, dim=-1)
                next_token = torch.multinomial(probabilities, 1)

                if next_token.item() == 2:  # EOS token
                    break

                outputs.append(next_token.item())
                decoder_input = next_token

            return outputs

# Create a wrapper model compatible with HuggingFace Trainer
class BiLSTMWrapper(nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.model = base_model

    def forward(self, input_ids=None, labels=None, attention_mask=None, **kwargs):
        # Forward pass through the model
        if labels is not None:
            # Training mode with labels
            outputs = self.model(src=input_ids, trg=labels)

            # Calculate loss - CrossEntropyLoss
            loss_fct = nn.CrossEntropyLoss(ignore_index=-100)
            loss = 0

            # Calculate loss for each position in the sequence
            for t in range(1, outputs.size(1)):
                loss += loss_fct(outputs[:, t, :], labels[:, t])

            # Average loss across positions
            loss = loss / (outputs.size(1) - 1)

            return {"loss": loss, "logits": outputs}
        else:
            # Inference mode
            return {"logits": self.model(src=input_ids)}

class BiLSTMSummarizer:
    def __init__(self, model_path, tokenizer, device='cuda'):
        self.device = torch.device(device if torch.cuda.is_available() else "cpu")
        self.tokenizer = tokenizer

        # Load model configuration
        checkpoint = torch.load(model_path, map_location=self.device)

        # Initialize model with saved parameters
        self.model = BiLSTMSeq2Seq(
            vocab_size=checkpoint['vocab_size'],
            embedding_dim=checkpoint['embedding_dim'],
            hidden_dim=checkpoint['hidden_dim'],
            num_layers=checkpoint.get('num_layers', 1)
        ).to(self.device)

        # Load weights
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.model.eval()

    def generate_summary(self, input_text, max_length=128):
        """Generate summary using BiLSTM model"""
        inputs = self.tokenizer(
            input_text,
            return_tensors='pt',
            max_length=512,
            truncation=True
        ).input_ids.to(self.device)

        with torch.no_grad():
            summary_ids = self.model.generate(inputs, max_len=max_length)
            return self.tokenizer.decode(summary_ids, skip_special_tokens=True)

    def evaluate(self, test_df, text_col='article', target_col='highlights'):
        """Evaluate BiLSTM performance using ROUGE metrics"""
        from rouge_score import rouge_scorer

        generated_summaries = []
        reference_summaries = []

        for _, row in test_df.iterrows():
            input_text = row[text_col]
            generated = self.generate_summary(input_text)
            generated_summaries.append(generated)
            reference_summaries.append(row[target_col])

        return self._calculate_rouge(generated_summaries, reference_summaries)

    def _calculate_rouge(self, generated, references):
        """Calculate ROUGE scores"""
        from rouge_score import rouge_scorer

        scorer = rouge_scorer.RougeScorer(
            ['rouge1', 'rouge2', 'rougeL'],
            use_stemmer=True
        )

        scores = {'rouge1': [], 'rouge2': [], 'rougeL': []}

        for gen, ref in zip(generated, references):
            score = scorer.score(ref, gen)
            scores['rouge1'].append(score['rouge1'].fmeasure)
            scores['rouge2'].append(score['rouge2'].fmeasure)
            scores['rougeL'].append(score['rougeL'].fmeasure)

        return {
            metric: sum(values)/len(values) if values else 0
            for metric, values in scores.items()
        }

"""# Test GNN + LSTM (Discarded due to bad performance)"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

def tokenize_document(document):
    # Split document into sentences
    sentences = sent_tokenize(document)

    # Preprocess each sentence
    processed_sentences = [preprocess_text(sentence) for sentence in sentences]

    # Remove empty sentences
    processed_sentences = [s for s in processed_sentences if s.strip()]

    return processed_sentences

# Apply preprocessing to the sampled data
train_sample['processed_article'] = train_sample['article'].apply(tokenize_document)
train_sample['processed_highlights'] = train_sample['highlights'].apply(tokenize_document)

# Create labels for extractive summarization (1 if sentence is in highlights, 0 otherwise)
def create_extractive_labels(article_sentences, highlight_sentences):
    labels = []
    for sentence in article_sentences:
        # Check if this sentence is similar to any highlight sentence
        is_in_highlights = any(
            similarity_score(sentence, highlight) > 0.7
            for highlight in highlight_sentences
        )
        labels.append(1 if is_in_highlights else 0)
    return labels

def similarity_score(sent1, sent2):
    # Simple word overlap similarity
    words1 = set(word_tokenize(sent1))
    words2 = set(word_tokenize(sent2))

    if not words1 or not words2:
        return 0

    overlap = len(words1.intersection(words2))
    return overlap / max(len(words1), len(words2))

# Create extractive labels
train_sample['extractive_labels'] = [
    create_extractive_labels(article, highlight)
    for article, highlight in zip(train_sample['processed_article'], train_sample['processed_highlights'])
]

from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import BertTokenizer, BertModel

class TextGraph:
    def __init__(self):
        self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        self.bert = BertModel.from_pretrained('bert-base-uncased')
        self.tfidf = TfidfVectorizer()

    def build_graph(self, document_sentences):
        # Extract all unique words
        all_words = set()
        for sentence in document_sentences:
            words = [word for word in word_tokenize(sentence) if word not in stopwords.words('english')]
            all_words.update(words)

        # Create node feature vectors
        sentence_features = self._encode_sentences(document_sentences)
        word_features = self._encode_words(list(all_words))

        # Calculate TF-IDF for edge weights
        self.tfidf.fit(document_sentences)
        tfidf_matrix = self.tfidf.transform(document_sentences)

        # Create edges (word-sentence connections)
        edges = []
        edge_weights = []

        for word_idx, word in enumerate(all_words):
            for sent_idx, sentence in enumerate(document_sentences):
                if word in word_tokenize(sentence):
                    # Word to sentence edge
                    edges.append([word_idx, sent_idx + len(all_words)])

                    # Get TF-IDF weight
                    word_id = self.tfidf.vocabulary_.get(word, -1)
                    weight = tfidf_matrix[sent_idx, word_id] if word_id != -1 else 0
                    edge_weights.append(weight)

        return {
            'sentence_features': sentence_features,
            'word_features': word_features,
            'edges': torch.tensor(edges).t().contiguous() if edges else torch.zeros((2, 0), dtype=torch.long),
            'edge_weights': torch.tensor(edge_weights) if edge_weights else torch.zeros(0),
            'sentences': document_sentences,
            'num_sentences': len(document_sentences),
            'num_words': len(all_words)
        }

    def _encode_sentences(self, sentences):
        # Encode sentences using BERT
        with torch.no_grad():
            encoded_sentences = []
            for sentence in sentences:
                inputs = self.tokenizer(sentence, return_tensors='pt', padding=True, truncation=True, max_length=128)
                outputs = self.bert(**inputs)
                # Use CLS token as sentence representation
                encoded_sentences.append(outputs.last_hidden_state[:, 0, :].squeeze())

            if encoded_sentences:
                return torch.stack(encoded_sentences)
            else:
                return torch.zeros((0, 768))

    def _encode_words(self, words):
        # Encode words using BERT
        with torch.no_grad():
            encoded_words = []
            for word in words:
                inputs = self.tokenizer(word, return_tensors='pt')
                outputs = self.bert(**inputs)
                # Use mean of token embeddings as word representation
                encoded_words.append(outputs.last_hidden_state.mean(dim=1).squeeze())

            if encoded_words:
                return torch.stack(encoded_words)
            else:
                return torch.zeros((0, 768))

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GATConv

class SummarizationGNN(nn.Module):
    def __init__(self, word_dim=768, sentence_dim=768, hidden_dim=256, num_heads=8):
        super(SummarizationGNN, self).__init__()

        # Word and sentence projections to the same dimension
        self.word_projection = nn.Linear(word_dim, hidden_dim)
        self.sentence_projection = nn.Linear(sentence_dim, hidden_dim)

        # GAT layers
        self.word_to_sentence = GATConv(hidden_dim, hidden_dim, heads=num_heads, concat=False)

        # Feed-forward networks after GAT
        self.sentence_ffn = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * 2),
            nn.ReLU(),
            nn.Linear(hidden_dim * 2, hidden_dim)
        )

        # Sentence classifier
        self.sentence_classifier = nn.Linear(hidden_dim, 1)

    def forward(self, graph):
        # Get features and structure
        word_features = graph['word_features']
        sentence_features = graph['sentence_features']
        edges = graph['edges']
        edge_weights = graph['edge_weights']
        num_words = graph['num_words']

        # Handle empty graphs
        if word_features.size(0) == 0 or sentence_features.size(0) == 0 or edges.size(1) == 0:
            return torch.zeros(sentence_features.size(0))

        # Project features to the same dimension
        word_features = self.word_projection(word_features)
        sentence_features = self.sentence_projection(sentence_features)

        # Combine features
        all_features = torch.cat([word_features, sentence_features], dim=0)

        # Word to sentence message passing
        updated_features = self.word_to_sentence(all_features, edges, edge_weights)

        # Apply FFN to sentence features
        sentence_updated = self.sentence_ffn(updated_features[num_words:])

        # Sentence classification
        sentence_scores = self.sentence_classifier(sentence_updated).squeeze(-1)

        return sentence_scores

import torch
from torch.utils.data import Dataset, DataLoader
from torch_geometric.data import Data
from tqdm import tqdm

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

class GraphDataset(Dataset):
    def __init__(self, dataframe, text_graph):
        self.dataframe = dataframe
        self.text_graph = text_graph

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        article_sentences = self.dataframe.iloc[idx]['processed_article']
        labels = self.dataframe.iloc[idx]['extractive_labels']

        # Build graph
        graph = self.text_graph.build_graph(article_sentences)

        # Convert labels to tensor and move to device
        graph['labels'] = torch.tensor(labels, dtype=torch.float).to(device)

        return graph

def collate_graphs(batch):
    return batch

# Initialize text graph builder
text_graph = TextGraph()

# Create dataset
train_dataset = GraphDataset(train_sample, text_graph)

# Create dataloader
train_loader = DataLoader(
    train_dataset,
    batch_size=1,  # Process one document at a time
    shuffle=True,
    collate_fn=collate_graphs
)

# Initialize model and move it to GPU
model = SummarizationGNN().to(device)

# Define loss function and optimizer
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 2



for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        graph = batch[0]  # Get the single graph from the batch

        # Skip empty graphs
        if graph['sentence_features'].size(0) == 0 or graph['word_features'].size(0) == 0 or graph['edges'].size(1) == 0:
            continue

        # Move all tensors to GPU
        graph['sentence_features'] = graph['sentence_features'].to(device)
        graph['word_features'] = graph['word_features'].to(device)
        graph['edges'] = graph['edges'].to(device)
        if 'edge_weights' in graph:
            graph['edge_weights'] = graph['edge_weights'].to(device)  # Move edge weights to GPU
        graph['labels'] = graph['labels'].to(device)

        # Forward pass
        scores = model(graph)

        # Calculate loss
        loss = criterion(scores, graph['labels'])

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

# Save the model
torch.save(model.state_dict(), "gnn_summarizer_model.pt")

# Define BiLSTM model architecture
class BiLSTMSeq2Seq(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers=1, dropout=0.1):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.num_layers = num_layers

        # Encoder (BiLSTM)
        self.encoder = nn.LSTM(embedding_dim, hidden_dim,
                             bidirectional=True, batch_first=True, num_layers=num_layers,
                             dropout=dropout if num_layers > 1 else 0)

        # Decoder (LSTM with attention)
        self.decoder = nn.LSTM(embedding_dim + hidden_dim*2, hidden_dim*2,  # Attention concatenation
                             batch_first=True, dropout=dropout, num_layers=1)

        # Attention mechanism
        self.attention = nn.Linear(hidden_dim*2 + hidden_dim*2, hidden_dim*2)
        self.v = nn.Linear(hidden_dim*2, 1, bias=False)

        # Final projection layer
        self.fc = nn.Linear(hidden_dim*2, vocab_size)

        # Dropout layers
        self.dropout = nn.Dropout(dropout)

    def forward(self, src, trg=None, max_len=128, teacher_forcing_ratio=0.5):
        batch_size = src.size(0)

        # Encoder Forward Pass
        embedded = self.dropout(self.embedding(src))
        encoder_outputs, (hidden, cell) = self.encoder(embedded)

        # Prepare decoder initial states
        hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1).unsqueeze(0)
        cell = torch.cat((cell[-2,:,:], cell[-1,:,:]), dim=1).unsqueeze(0)

        # Decoder Setup
        if trg is None:
            trg = torch.zeros((batch_size, max_len), dtype=torch.long, device=src.device)
            trg[:,0] = 1  # Start with SOS token

        decoder_input = self.embedding(trg[:,0].unsqueeze(1))
        outputs = torch.zeros(max_len, batch_size, self.fc.out_features, device=src.device)

        # Decoding Loop
        for t in range(1, max_len):
            # Attention Calculation
            energy = torch.tanh(self.attention(torch.cat((
                hidden.repeat(encoder_outputs.size(1), 1, 1).permute(1,0,2),
                encoder_outputs
            ), dim=2)))

            attention = F.softmax(self.v(energy).squeeze(2), dim=1)
            context = torch.bmm(attention.unsqueeze(1), encoder_outputs)

            # Decoder Step
            decoder_output, (hidden, cell) = self.decoder(
                torch.cat((decoder_input, context), dim=2),
                (hidden, cell)
            )

            # Project to vocabulary space
            output = self.fc(decoder_output.squeeze(1))
            outputs[t] = output

            # Teacher Forcing
            use_teacher_forcing = random.random() < teacher_forcing_ratio
            top1 = output.argmax(1)

            decoder_input = self.embedding(trg[:,t].unsqueeze(1) if use_teacher_forcing else top1.unsqueeze(1))
            decoder_input = self.dropout(decoder_input)

        return outputs.permute(1, 0, 2)

    def generate(self, src, max_len=128, temperature=1.0):
        with torch.no_grad():
            # Encoder forward pass
            encoder_outputs, (hidden, cell) = self.encoder(self.embedding(src))

            # Prepare decoder initial states
            hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1).unsqueeze(0)
            cell = torch.cat((cell[-2,:,:], cell[-1,:,:]), dim=1).unsqueeze(0)

            outputs = []
            decoder_input = torch.tensor([[1]], device=src.device)  # SOS token

            for _ in range(max_len):
                decoder_emb = self.embedding(decoder_input)

                # Attention
                energy = torch.tanh(self.attention(torch.cat((
                    hidden.repeat(encoder_outputs.size(1), 1, 1).permute(1,0,2),
                    encoder_outputs
                ), dim=2)))

                attention = F.softmax(self.v(energy).squeeze(2), dim=1)
                context = torch.bmm(attention.unsqueeze(1), encoder_outputs)

                # Decoder step
                decoder_output, (hidden, cell) = self.decoder(
                    torch.cat((decoder_emb, context), dim=2),
                    (hidden, cell)
                )

                # Output projection
                logits = self.fc(decoder_output.squeeze(1)) / temperature
                probabilities = F.softmax(logits, dim=-1)
                next_token = torch.multinomial(probabilities, 1)

                if next_token.item() == 2:  # EOS token
                    break

                outputs.append(next_token.item())
                decoder_input = next_token

            return outputs

# Create a wrapper model compatible with HuggingFace Trainer
class BiLSTMWrapper(nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.model = base_model

    def forward(self, input_ids=None, labels=None, attention_mask=None, **kwargs):
        # Forward pass through the model
        if labels is not None:
            # Training mode with labels
            outputs = self.model(src=input_ids, trg=labels)

            # Calculate loss - CrossEntropyLoss
            loss_fct = nn.CrossEntropyLoss(ignore_index=-100)
            loss = 0

            # Calculate loss for each position in the sequence
            for t in range(1, outputs.size(1)):
                loss += loss_fct(outputs[:, t, :], labels[:, t])

            # Average loss across positions
            loss = loss / (outputs.size(1) - 1)

            return {"loss": loss, "logits": outputs}
        else:
            # Inference mode
            return {"logits": self.model(src=input_ids)}

import wandb
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
secret_value_0 = user_secrets.get_secret("wandb_api_key")
wandb.login(key=secret_value_0)
wandb.init(project="BiLSTMs + GNN")
# Define training arguments
training_args = TrainingArguments(
    output_dir="./biLSTMS_finetuned",
    evaluation_strategy="epoch",  # Enables evaluation every epoch
    save_strategy="epoch",        # Saves model every epoch
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=500,
    save_total_limit=0,  # Limits saved checkpoints to avoid storage issues
    load_best_model_at_end=True,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,  # Include validation set
)

# Train the model
trainer.train()

# Install required packages
import sys
import subprocess
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'datasets', 'transformers','wandb'])

import datasets
import pandas as pd
import numpy as np
import torch
import random
from tqdm import tqdm
import wandb

# Set random seed for reproducibility
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

# Initialize wandb
wandb.init(project="bilstm-summarization", name="bilstm-seq2seq")

# Load the CNN/DailyMail dataset
cnn_dataset = datasets.load_dataset("abisee/cnn_dailymail", "3.0.0")

# Convert to pandas DataFrame for easier manipulation
train_df = pd.DataFrame(cnn_dataset["train"])
val_df = pd.DataFrame(cnn_dataset["validation"])
test_df = pd.DataFrame(cnn_dataset["test"])

# Sample a smaller portion of the training data for faster processing
sample_size = int(len(train_df) * 0.001)
train_sample = train_df.sample(n=sample_size, random_state=42)

print(f"Full training set size: {len(train_df)}")
print(f"Sample size: {len(train_sample)}")

# Log dataset info to wandb
wandb.config.update({
    "dataset": "CNN/DailyMail",
    "full_train_size": len(train_df),
    "sample_size": len(train_sample),
    "val_size": len(val_df),
    "test_size": len(test_df)
})

from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, TrainingArguments, Trainer, EarlyStoppingCallback,TrainerCallback
import torch.nn as nn
import torch.nn.functional as F

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")